trigger:
- master

pool:
  vmImage: 'macos-latest'

jobs:
- job: Build
  displayName: 'Build job'
  steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew.bat'
      gradleOptions: '-Xmx2048m -Dfile.encoding=UTF-8'
      publishJUnitResults: true
      tasks: 'assembleDebug'


  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'

